// Curated rules-scenario parity test: C++ rules port vs the PyVariant oracle.
//
// Companion to parity_test.cc. That test replays a large *random*-game corpus
// (great breadth, but it almost never reaches the rare corners that decide
// correctness). This one replays a small *curated* corpus — one position per
// rule corner from chessckers.md (the §3B cadence/rim/off-grid worked examples,
// the §4 capture Mandate, the §5 win conditions, promotion, the opening
// double-move) plus the post-move position for the transitions whose point is a
// terminal/win state. Think Kiwipete/Position3-6 to parity_test.cc's startpos
// perft. The corpus is generated by engine/scripts/gen_rules_scenarios.py and
// regenerated after any rule change; expected values are PyVariant's, never
// hand-typed.
//
// Each corpus line is:
//   {"fen":"<chessckers FEN>","legal":[<uci>,...sorted],
//    "status":"<''|variantEnd|mate|stalemate>","winner":"<''|white|black>",
//    "apply":{<uci>:<resulting FEN>,...}}     // "apply" absent on terminals
// and this test asserts the C++ port agrees on all four:
//   (a) the legal move set        (cc::gen_legal_native),
//   (b) status / winner           (cc::detect_status),
//   (c) per-move applied FEN       (serialize_fen(apply_native(...))) — the
//       *apply* path (promotion, charge demotion, captures, the {wm}/{r8}
//       turn-state machine) that the move-gen/status corpus never exercises.
//
// Standalone on purpose (plain main() + counters, no gtest), matching
// parity_test.cc: the stock lc0 gtest suite tests FIDE chess, which this fork
// does not play. CcRulesScenarios links Accelerate (via deps) because
// gen_legal_native pulls in the BLAS-using nn.hpp. Run as:
//   rules_scenarios_test <path-to-rules_scenarios.jsonl>

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

#include "chessckers/apply.hpp"
#include "chessckers/json_parse.hpp"
#include "chessckers/native_move.hpp"

using namespace cc;

static void print_capped(const char* label, const std::vector<std::string>& v, size_t cap) {
    printf("      %s (%zu):", label, v.size());
    for (size_t i = 0; i < v.size() && i < cap; ++i) printf(" %s", v[i].c_str());
    if (v.size() > cap) printf(" ...");
    printf("\n");
}

int main(int argc, char** argv) {
    if (argc < 2) {
        printf("usage: %s <rules_scenarios.jsonl>\n", argv[0]);
        return 2;
    }
    std::ifstream in(argv[1]);
    if (!in) {
        printf("error: cannot open corpus %s\n", argv[1]);
        return 2;
    }

    int checked = 0;
    int gen_mismatch = 0;
    int status_mismatch = 0;
    int apply_mismatch = 0;
    int apply_checked = 0;
    const int kReportCap = 8;  // small corpus: report a bit more before capping

    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        const JsonValue v = JsonParser(line).parse();

        const JsonValue* fen_v = v.find("fen");
        const JsonValue* legal_v = v.find("legal");
        const JsonValue* status_v = v.find("status");
        const JsonValue* winner_v = v.find("winner");
        const JsonValue* apply_v = v.find("apply");
        const std::string fen = fen_v ? fen_v->str : "";
        const std::string exp_status = status_v ? status_v->str : "";
        const std::string exp_winner = winner_v ? winner_v->str : "";

        std::vector<std::string> expected;  // already sorted in the corpus
        if (legal_v) {
            for (const JsonValue& e : legal_v->arr) expected.push_back(e.str);
        }

        const Board b = parse_fen(fen);

        // (a) legal move set: collect every generated uci, sort, compare exactly.
        std::vector<NativeMove> moves = gen_legal_native(b);
        std::vector<std::string> got;
        for (const NativeMove& m : moves) got.push_back(m.uci);
        std::sort(got.begin(), got.end());

        if (got != expected) {
            ++gen_mismatch;
            if (gen_mismatch <= kReportCap) {
                printf("GEN MISMATCH: %s\n", fen.c_str());
                std::vector<std::string> missing, extra;
                std::set_difference(expected.begin(), expected.end(), got.begin(), got.end(),
                                    std::back_inserter(missing));
                std::set_difference(got.begin(), got.end(), expected.begin(), expected.end(),
                                    std::back_inserter(extra));
                print_capped("missing", missing, kReportCap);
                print_capped("extra", extra, kReportCap);
            }
        }

        // (b) status + winner.
        const Status st = detect_status(b);
        if (st.status != exp_status || st.winner != exp_winner) {
            ++status_mismatch;
            if (status_mismatch <= kReportCap) {
                printf("STATUS MISMATCH: %s\n", fen.c_str());
                printf("      want status='%s' winner='%s'  got status='%s' winner='%s'\n",
                       exp_status.c_str(), exp_winner.c_str(), st.status.c_str(),
                       st.winner.c_str());
            }
        }

        // (c) apply parity: for every generated move, serialize_fen(apply_native)
        // must equal the oracle's resulting FEN (looked up by uci). Only checks
        // moves the gen agreed on (a mismatched gen is already reported in (a)).
        if (apply_v && apply_v->is_obj()) {
            for (const NativeMove& m : moves) {
                const JsonValue* want = apply_v->find(m.uci);
                if (!want || want->type != JsonValue::Str) continue;  // gen-only extra
                ++apply_checked;
                const std::string got_fen = serialize_fen(apply_native(b, m));
                if (got_fen != want->str) {
                    ++apply_mismatch;
                    if (apply_mismatch <= kReportCap) {
                        printf("APPLY MISMATCH: %s  move=%s\n", fen.c_str(), m.uci.c_str());
                        printf("      want %s\n      got  %s\n", want->str.c_str(),
                               got_fen.c_str());
                    }
                }
            }
        }

        ++checked;
    }

    printf("checked %d: gen_mismatch=%d status_mismatch=%d apply_mismatch=%d (apply_checked=%d)\n",
           checked, gen_mismatch, status_mismatch, apply_mismatch, apply_checked);
    return (gen_mismatch || status_mismatch || apply_mismatch) ? 1 : 0;
}
